# Generated by Django 5.2.6 on 2025-11-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("timeAgo", models.CharField(default="Just now", max_length=50)),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                ("requester_name", models.CharField(max_length=100)),
                ("requester_initials", models.CharField(max_length=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
